; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=AstitvaDrugHouse
AppVersion=1.2
DefaultDirName={autopf}\AstitvaDrugHouse
DefaultGroupName=AstitvaDrugHouse
OutputDir=Output
OutputBaseFilename=AstitvaDrugHouse_Setup
Compression=lzma
SolidCompression=yes
; Prevent users from installing on top of a running app
CloseApplications=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked

[Files]
; NOTE: These paths assume this .iss file is in E:\ASTITVA-DRUG-HOUSE (Root)
; If .iss is in Backend, remove "Backend\" from the start of paths.

; 1. The Main Executable (Explicitly listed first)
Source: "Backend\dist\AstitvaDrugHouse\AstitvaDrugHouse.exe"; DestDir: "{app}"; Flags: ignoreversion

; 2. All other files (Recursively copy everything else, including Updater and _internal)
Source: "Backend\dist\AstitvaDrugHouse\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\AstitvaDrugHouse"; Filename: "{app}\AstitvaDrugHouse.exe"
Name: "{autodesktop}\AstitvaDrugHouse"; Filename: "{app}\AstitvaDrugHouse.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\AstitvaDrugHouse.exe"; Description: "Launch AstitvaDrugHouse"; Flags: nowait postinstall skipifsilent